spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: user_user
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update

eureka.client.service-url.defaultZone: http://localhost:8761/eureka
management.endpoints.web.exposure.include: "*"

springdoc.api-docs.path: /v3/api-docs
springdoc.swagger-ui.path: /swagger
